version: "3.2"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
      - timezone:/etc/timezone:ro
      - localtime:/etc/localtime:ro
    ports:
      - "3003:3000"
      - "222:22"
networks:
  gitea:

volumes:
  gitea:
    driver: local
  timezone:
    driver: local
  localtime:
    driver: local